version: '2'
services:
  emby:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - VER
        - BUILD
    container_name: emby-new
    image: nemd/docker-emby:${VER}.${BUILD}
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - /srv/dockstorage/emby/conf/:/config
      - /srv/storage/media:/media
    restart: always
volumes:
  emby-config:
    driver: local
