version: '2'
services:
  emby:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: emby-tst
    image: nemd/docker-emby:00
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      # - /srv/dockstorage/emby/conf:/config
      # - /srv/storage/media:/media
      - emby-config:/config
    restart: always

volumes:
  emby-config:
    driver: local
